### ISSUE TITLE
Crashes on Tap 13 data

### ISSUE THREAD

**Issue by Munter** [scottcorgan/tap-spec#28]
This reporter crashes when piping in [Tap 13 data](https://gist.github.com/Munter/c634d3e4268a72cd1326#file-mntr-dk-tap):

```
$ hyperlink https://mntr.dk/ -r | tap-spec

  Crawling internal assets

    ✓ loading https://mntr.dk/
    ✓ loading https://mntr.dk/favicon.ico
    ✓ loading https://mntr.dk/assets/images/favicon/152.png
    ✓ loading https://mntr.dk/assets/images/favicon/144.png
    ✓ loading https://mntr.dk/assets/images/favicon/120.png
    ✓ loading https://mntr.dk/assets/images/favicon/114.png
    ✓ loading https://mntr.dk/assets/images/favicon/72.png
    ✓ loading https://mntr.dk/assets/images/favicon/57.png
    ✓ loading https://mntr.dk/assets/images/favicon/32.png
    ✓ loading https://mntr.dk/assets/images/favicon/16.png
    ✓ loading https://mntr.dk/assets/css/main.css
    ✓ loading https://mntr.dk/assets/css/syntax.css
    ✓ loading https://mntr.dk/feed.xml
    ✓ loading https://mntr.dk/assets/images/logo-white.svg
    ✓ loading https://mntr.dk/2014/getting-started-with-assetgraph/
    ✓ loading https://mntr.dk/2014/getting-started-with-assetgraph/#toc_10
    ✓ loading https://mntr.dk/2014/getting-started-with-assetgraph/#toc_11
    ✓ loading https://mntr.dk/2014/getting-started-with-assetgraph/#toc_12
    ✓ loading https://mntr.dk/2014/i-love-the-unix-philisophy-but/
    ✓ loading https://mntr.dk/2014/push-the-post-get-paradigm/
    ✓ loading https://mntr.dk/assets/images/munter.jpg
    ✓ loading https://mntr.dk/cdn-cgi/l/email-protection#9af7eff4eeffe8b1f7f4eee8dafceff7f6ffb4fef1
    ✓ loading https://mntr.dk/cdn-cgi/styles/cf.errors.css
    ✓ loading https://mntr.dk/cdn-cgi/styles/cf.errors.ie.css
    ✓ loading https://mntr.dk/cdn-cgi/scripts/jquery.min.js
    ✓ loading https://mntr.dk/cdn-cgi/scripts/zepto.min.js
    ✓ loading https://mntr.dk/cdn-cgi/scripts/cf.common.js
    ✓ loading https://mntr.dk/cdn-cgi/l/email-protection#1b766e756f7e693076756f695b7d6e76777e357f70
    ✓ loading https://mntr.dk/cdn-cgi/l/email-protection#402d352e3425326b2d2e34320026352d2c256e242b
    ✓ loading https://mntr.dk/assets/images/social/social-twitter.svg
    ✓ loading https://mntr.dk/assets/images/social/social-github.svg
    ✓ loading https://mntr.dk/assets/images/social/social-gplus.svg
    ✓ loading https://mntr.dk/assets/images/social/social-linkedin.svg
    ✓ loading https://mntr.dk/assets/images/social/social-email.svg
    ✓ loading https://mntr.dk/assets/images/social/social-feed.svg
    ✓ loading https://mntr.dk/cdn-cgi/l/email-protection#375a42594352451c5a5943457751425a5b5219535c
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300.eot
    ✓ loading https://mntr.dk/cdn-cgi/l/email-protection#29445c475d4c5b0244475d5b694f5c44454c074d42
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300.eot?#iefix
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300.woff
    ✓ loading https://mntr.dk/cdn-cgi/l/email-protection#eb869e859f8e99c086859f99ab8d9e86878ec58f80
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300.ttf
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300.svg#open_sanssemibold
    ✓ loading https://mntr.dk/cdn-cgi/l/email-protection#dab7afb4aebfa8f1b7b4aea89abcafb7b6bff4beb1
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400.eot
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400.eot?#iefix
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400.woff
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400.ttf
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400.svg#open_sansregular
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-600.eot
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-600.eot?#iefix
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-600.woff
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-600.ttf
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-600.svg#open_sanssemibold
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-700.eot
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-700.eot?#iefix
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-700.woff
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-700.ttf
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-700.svg#open_sansbold
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300i.eot
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300i.eot?#iefix
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300i.woff
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300i.ttf
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-300i.svg#open_sanslight_italic
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400i.eot
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400i.eot?#iefix
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400i.woff
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400i.ttf
    ✓ loading https://mntr.dk/cdn-cgi/styles/fonts/opensans-400i.svg#open_sansitalic
    ✓ loading https://mntr.dk/cdn-cgi/images/error_icons.png
    ✓ loading https://mntr.dk/cdn-cgi/images/icon-exclamation.png?1376755637
    ✓ loading https://mntr.dk/cdn-cgi/images/browser-bar.png?1376755637
    ✓ URI should have not redirects - https://twitter.com/intent/tweet
    ✓ URI should have not redirects - https://www.youtube.com/watch?v=N_gRlmmF4Rc
    ✓ URI should have not redirects - http://stevesouders.com/hpws/rules.php

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: write EPIPE
    at errnoException (net.js:904:11)
    at Object.afterWrite (net.js:720:19)
```

**Comment by scottcorgan** [comment]
Investigating. I'll have a fix out in the next day or 2, among other improvements.

**Comment by scottcorgan** [comment]
Apologize. Been swamped. Working on next release.

**Comment by Munter** [comment]
I very much know that feeling. No need for apologies. Thank you for the good work

**Comment by scottcorgan** [comment]
Is this still an issu ein `4.0.0`?

**Comment by Munter** [comment]
`4.0.0` no longer crashes. But instead it now seems to simply halt at the same place as before. When encoutering the first error [in this tap file](https://gist.githubusercontent.com/Munter/c634d3e4268a72cd1326/raw/ce8e6212ef1e0b4f97184f331f79bb9c1c602dc1/mntr.dk.tap) it stops

**Comment by keithamus** [comment]
FYI this issue is because tap-out (the parser used by tap-spec) does not support YAML1.2 blocks. See this issue: https://github.com/scottcorgan/tap-out/issues/17

@Munter in your TAP file you have the following:

```js
not ok 75 URI should have not redirects - http://copenhagenjs.dk/
  ---
    operator: noRedirects
    expected: "200 http://copenhagenjs.dk/"
    actual:   "302 http://copenhagenjs.dk/ --> 200 http://copenhagenjs.dk/"
    at: https://mntr.dk/
        https://mntr.dk/2014/getting-started-with-assetgraph/
        https://mntr.dk/2014/i-love-the-unix-philisophy-but/
        https://mntr.dk/2014/push-the-post-get-paradigm/
  ...
```

Specifically it's failing at the line after `at` - because `tap-out` does not handle multiline yaml values.

### Solution

Fix https://github.com/scottcorgan/tap-out/issues/17 - the upstream issue.

**Comment by Munter** [comment]
Thanks for looking into this. Investigation is usually the hardest part :)

**Comment by scottcorgan** [comment]
@keithamus appreciate all the research and detailed issues. I'll jump on fixing tap-out. I have a planned rewrite the simplify collaboration on the repo.

@Munter appreciate the patience.

**Comment by scottcorgan** [comment]
I've started a complete rewrite that's way less hack. `2.0` will fix this bug.

**Comment by scottcorgan** [comment]
I have been working on a collection of packages under the org [tap-format](https://github.com/tap-format) as sequels to my few [tap-[formatter]](https://github.com/search?utf8=%E2%9C%93&q=repo%3Ascottcorgan%2Ftap-spec+repo%3Ascottcorgan%2Ftap-dot+repo%3Ascottcorgan%2Ftap-out&type=Repositories&ref=searchresults) modules.

https://github.com/tap-format/spec will be the replacement for this. It's basically done, just needs documentation and screenshots/video-gifs.

**Comment by bdesham** [comment]
Any news on this?

**Comment by scottcorgan** [comment]
Anyone open to a PR for this? My time is limited right now.

**Comment by robwold** [comment]
I wrote this: https://github.com/robwold/tap-spec-report-bug
Intending to file it as a separate issue, but have looked and realised it's probably this.

I wouldn't mind contributing a PR, but would it be to this repo, or to https://github.com/scottcorgan/tap-out/issues/17 or somewhere else? In that issue you talk about deprecating tap-out in favour of another project, and it's not clear (to me at least) what the current state of affairs is.

**Comment by scottcorgan** [comment]
@robwold most likely the PR is going to be on tap-out, and then a PR on this repo to update the tap-out version.
