### ISSUE TITLE
Some info from failed spec is lost (v4.0.0)

### ISSUE THREAD

**Issue by tomekwi** [scottcorgan/tap-spec#34]
Raw output from *tape*:

```
not ok 4 • a cacheable output channel `state`
  ---
    operator: deepEqual
    expected:
      [ { property: 'on', type: 'function' }, { property: 'off', type: 'function' }, { property: 'when', type: 'function' } ]
    actual:
      [ { property: 'on', type: 'function' }, { property: 'when', type: 'function' }, { property: 'off', type: 'function' } ]
    at: Test.<anonymous> (/home/tomekwi/Libraries/studio-b12/bare-select/test/model.test.js:58:6)
  ...
```

Here’s how *tap-spec v2.x* displayed that:

![image](https://cloud.githubusercontent.com/assets/4624660/7889230/833a5c74-063e-11e5-8c54-446ea331b7ef.png)

*tap-spec v4.0.0* has better looks, but loses the `actual: …` part:

![image](https://cloud.githubusercontent.com/assets/4624660/7889241/9fa11830-063e-11e5-9ea3-18e3d4f945aa.png)

It’d be great to have it back :)

**Comment by scottcorgan** [comment]
Fixed in version `4.0.0`

**Comment by tomekwi** [comment]
Actually no, this is an issue with *v4.0.0*. Read it carefully.

**Comment by scottcorgan** [comment]
Sorry for such a delay. Do you have sample code I can run to reproduce?

**Comment by tomekwi** [comment]
Sorry for such a delay as well :) I haven’t run into the issue again until today.

To reproduce:

```sh
git clone git@github.com:studio-b12/doxie.append
cd doxie.append
git checkout 324619f
npm install; npm test
```

Raw output from tape:

```
$ node .es5/test.js 
TAP version 13
# Programmatic API:  Sticks a string at the end of the docs.
not ok 1 TypeError: undefined is not a function
  ---
    operator: error
    expected: undefined
    actual:   [TypeError: undefined is not a function]
    at: Test.assert (/home/tomekwi/Projects/Studio B12/doxie.append/node_modules/tape/lib/test.js:207:17)
    stack:
      TypeError: undefined is not a function
        at /home/tomekwi/Projects/Studio B12/doxie.append/.es5/module/index.js:10:47
        at Test.<anonymous> (/home/tomekwi/Projects/Studio B12/doxie.append/.es5/test/index.test.js:22:50)
        at Test.bound [as _cb] (/home/tomekwi/Projects/Studio B12/doxie.append/node_modules/tape/lib/test.js:62:32)
        at Test.exports.Test.run (/home/tomekwi/Projects/Studio B12/doxie.append/node_modules/tape-catch/index.js:17:10)
        at Test.bound [as run] (/home/tomekwi/Projects/Studio B12/doxie.append/node_modules/tape/lib/test.js:62:32)
        at Immediate.next [as _onImmediate] (/home/tomekwi/Projects/Studio B12/doxie.append/node_modules/tape/lib/results.js:67:15)
        at processImmediate [as _immediateCallback] (timers.js:367:17)
  ...

1..1
# tests 1
# pass  0
# fail  1
```

Output from tap-spec (the `stack` is lost):

![image](https://cloud.githubusercontent.com/assets/4624660/8774046/03bd949c-2eda-11e5-883d-62fbff75f0a4.png)

And here’s the same output live on travis: https://travis-ci.org/studio-b12/doxie.append/jobs/71742577

**Comment by tomekwi** [comment]
It’s fine with *v2* by the way:

```sh
git checkout b3dba33
```

Or just peek here: https://travis-ci.org/studio-b12/doxie.append/jobs/71743643

**Comment by tomekwi** [comment]
Hi! I’ve just checked it with v4.1.0. The OP case is now ok, but the latter (https://github.com/scottcorgan/tap-spec/issues/34#issuecomment-122841681) still isn’t. The `stack` gets lost:

```
$ cat <<——— | tap-spec
TAP version 13
# Programmatic API:  Sticks a string at the end of the docs.
not ok 1 TypeError: undefined is not a function
 ---
   operator: error
   expected: undefined
   actual:   [TypeError: undefined is not a function]
   at: Test.assert (…/node_modules/tape/lib/test.js:207:17)
   stack:
     TypeError: undefined is not a function
       at …/.es5/module/index.js:10:47
       at Test.<anonymous> (…/.es5/test/index.test.js:22:50)
       at Test.bound [as _cb] (…/node_modules/tape/lib/test.js:62:32)
       at Test.exports.Test.run (…/node_modules/tape-catch/index.js:17:10)
       at Test.bound [as run] (…/node_modules/tape/lib/test.js:62:32)
       at Immediate.next [as _onImmediate] (…/node_modules/tape/lib/results.js:67:15)
       at processImmediate [as _immediateCallback] (timers.js:367:17)
 ...

1..1
# tests 1
# pass  0
# fail  1
———

  Programmatic API:  Sticks a string at the end of the docs.


    ✖ TypeError: undefined is not a function
    -----------------------------------------
      operator: error
      expected: undefined
      actual:   [TypeError: undefined is not a function]
      at: Test.assert (…/node_modules/tape/lib/test.js:207:17)
      stack:




  Failed Tests: There was 1 failure

    Programmatic API:  Sticks a string at the end of the docs.

      ✖ TypeError: undefined is not a function


  total:     1
  passing:   0
  failing:   1
  duration:  13ms

```

To reproduce just paste everything up to and including the closing `———` into a POSIX-compliant shell (e.g. *bash*).

**Comment by keithamus** [comment]
Hey @scottcorgan  - @tomekwi's latest comment looks like its a duplicate issue of https://github.com/scottcorgan/tap-spec/issues/28. (Its not properly passing the multiline YAML value - the stack value).

I think if @tomekwi is happy that v4.1.0 fixes his original issue (undefined values not being reported), then this issue can be closed, as the stack issue is - as I say, a dupe of #28.

**Comment by tomekwi** [comment]
Yeah, thanks for taking the time to look into this @keithamus!

**Comment by tomekwi** [comment]
And thanks for the great tool @scottcorgan!!!
